# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d94f305cd6588a9222416532c9479edb898c814215beb6e81e86dbdbd204d5dd4ac2ee1ab674cd0232f7d272ef2258fe20703501bcd33e2aaa82ee0e750928c3

test:
  secret_key_base: 0e4f7de3771bf4fa7efa9e3e788d6b50e1cdf6914efeb165bb525067363fe9ae850fa9bf204cfda064f53966be32f074fbb1f45928549653dcccad833baee108

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
